AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  ParameterPrefix:
    Type: String
    Default: /global/alb
  SecurityGroup:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::SecurityGroup::Id>
    Default: /global/defaultSecurityGroup
  Subnets:
    Type: AWS::SSM::Parameter::Value<List<AWS::EC2::Subnet::Id>>
    Default: /global/subnets
  SslCertificateArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /kahgeh.com/SslCertificateArn
Resources:
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internal
      SecurityGroups:
        - !Ref SecurityGroup
      Subnets: !Ref Subnets
  HttpsListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref SslCertificateArn
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            StatusCode: "200"
            MessageBody: |
              You've reached the fallback for this load balancer. 
              That means you didn't use a domain name that matches 
              any of the listener rules.
  HttpListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Port: "443"
            StatusCode: HTTP_301
  ListenerOutputParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${ParameterPrefix}/listenerArn
      Value: !Ref HttpsListener
      Type: String
  LoadBalancerHostedZoneIdOutputParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${ParameterPrefix}/canonicalHostedZoneID
      Value: !GetAtt LoadBalancer.CanonicalHostedZoneID
      Type: String
  LoadBalancerDnsNameOutputParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${ParameterPrefix}/dnsName
      Value: !GetAtt LoadBalancer.DNSName
      Type: String
